### ISSUE TITLE
Tests are failing on Windows OS

### ISSUE THREAD

**Issue by tbrowder** [Leont/path-finder#10]
See for example File::Find at [raku-community-modules](https://github.com/raku-community-modules/File-Find).

**Comment by Leont** [comment]
Could you paste me such test results?

**Comment by tbrowder** [comment]
Yes, I will do a test run on Github with debugging turned on. I should have said that was on Github, not on my Windows host (which does not have a Rakudo dev setup).

**Comment by tbrowder** [comment]
Well, that's dumb. I can't find which module test gave the result. I'll close this and reopen if I find it.
