### ISSUE TITLE
Glob is missing '[A-Z]' syntax, thus unable to restrict a letter to a subset of all chars

### ISSUE THREAD

**Issue by tbrowder** [Leont/path-finder#7]
And it looks like IO::Glob has the same problem. I've also tried using a Raku regex but couldn't get it to work.

**Comment by Leont** [comment]
I would recommend filing the issue at [IO::Glob](https://github.com/zostay/raku-IO-Glob/issues)

**Comment by Leont** [comment]
This is resolved in `Path::Finder` `0.3.0`. I've written a new glob implementation that includes a number of missing features (as well as allowing me to be smarter about skipping directories).
